"""initial_schema_with_all_columns

Revision ID: dac84a00baf4
Revises: 
Create Date: 2026-05-09 13:21:55.104593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dac84a00baf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_weighment_sequences_year_code', table_name='weighment_sequences')
    op.create_index(op.f('ix_weighment_sequences_year_code'), 'weighment_sequences', ['year_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weighment_sequences_year_code'), table_name='weighment_sequences')
    op.create_index('uq_weighment_sequences_year_code', 'weighment_sequences', ['year_code'], unique=True)
    # ### end Alembic commands ###
